@ppedv.CrustControl.Web.Api_HostAddress = https://localhost:7291

GET {{ppedv.CrustControl.Web.Api_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{ppedv.CrustControl.Web.Api_HostAddress}}/api/pizza

###
